#!/usr/bin/python

#/*******************************************************************************************************************
# * Project Euler - Problem 2
# *
# * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# * the  first 10 terms will be:
# *                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# * Find the sum of all the even-valued terms in the sequence which do not exceed four million.
# *
# *******************************************************************************************************************/

def problem2():
	op1 = 0; op2 = 1; result = 0; sum = 0	;
	while(result <= 4000000):
		result = op1 + op2
		op1 = op2;
		op2 = result
		if (result % 2 == 0):
			sum = sum + result
	return sum


print "The answer of problem2 is %i" % (problem2())
